global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'adaptive-app'
    static_configs:
      - targets: ['adaptive-app:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'adaptive-node'
    static_configs:
      - targets: ['adaptive-node:8545']
    metrics_path: '/debug/metrics'
    scrape_interval: 30s

  - job_name: 'adaptive-redis'
    static_configs:
      - targets: ['adaptive-redis:6379']
    scrape_interval: 30s

  - job_name: 'adaptive-db'
    static_configs:
      - targets: ['adaptive-db:5432']
    scrape_interval: 30s
